# Generated by Django 4.1.5 on 2023-06-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='Aadhar_Number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='Date_Of_Birth',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='Date_Of_Joining',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='Phone_Number',
            field=models.IntegerField(),
        ),
    ]
