# Generated by Django 4.1.5 on 2023-06-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0003_employee_details_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='Date_Of_Joining',
            field=models.DateField(),
        ),
    ]
