# Generated by Django 4.1.5 on 2023-06-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0008_alter_employee_details_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='Aadhar_Number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='Account_Number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='Basic_Pay',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='Casual_Leave_Permonth',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='Conveyance_Allowence',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='ESI',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='Experience_years',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='General_Allowence',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='HRA',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='Medical_Allowence',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='Net_Salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='PF',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='Professional_Tax',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='RD',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='Working_Hours',
            field=models.IntegerField(null=True),
        ),
    ]
