# Generated by Django 4.1.5 on 2023-06-22 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0009_alter_employee_details_aadhar_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_details',
            old_name='Referece_Name',
            new_name='Reference_Name',
        ),
    ]
