# Generated by Django 4.1.5 on 2023-06-23 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0011_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Api_app.department'),
        ),
    ]
