# Generated by Django 4.1.5 on 2023-06-26 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0013_alter_employee_details_epf_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_details',
            old_name='Department',
            new_name='Department_name',
        ),
    ]
