# Generated by Django 4.1.5 on 2023-06-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0014_rename_department_employee_details_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_details',
            old_name='Department_name',
            new_name='Department',
        ),
    ]
