# Generated by Django 4.1.5 on 2023-06-26 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0015_rename_department_name_employee_details_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='Designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Api_app.designation'),
        ),
    ]
