# Generated by Django 4.1.5 on 2023-06-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0018_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Status',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
