# Generated by Django 4.1.5 on 2023-06-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0019_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
