# Generated by Django 4.1.5 on 2023-06-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0020_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Status',
            field=models.CharField(choices=[('Present', 1), ('Absent', 2), ('Casual', 3), ('Sick', 4)], max_length=100, null=True),
        ),
    ]
