# Generated by Django 4.1.5 on 2023-06-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0021_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Present'), (2, 'Absent'), (3, 'Casual'), (4, 'Sick')], null=True),
        ),
    ]
