# Generated by Django 4.1.5 on 2023-06-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0022_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
