# Generated by Django 4.1.5 on 2023-07-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0025_alter_attendance_date_alter_attendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='log_entrys_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_entry', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=200)),
                ('trace_back', models.CharField(blank=True, max_length=200, null=True)),
                ('IP_address', models.CharField(blank=True, max_length=200, null=True)),
                ('path', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
